#!/bin/sh

for file in "${DOTFILES}"/funcs/*; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file"
done

function _id () {
    echo $(date +"%Y%m%d%H%M")
}

function arch-workspace () {
    local workspace_dir="${1}"
    local archive_name=${2:-$(basename $workspace_dir).zip}
    local archive_dir="${RW_WORKSPACES_DIR}/z_archive/"
    local archive_full_path="${archive_dir}/${archive_name}"
    echo "Archiving $workspace_dir to $archive_full_path"
    mkdir -p "$archive_dir"
    zip -r $archive_full_path $workspace_dir
}

function zip-dirs () {
    for dir in ./*; do
        if [[ -d "$dir" ]]; then
            archive_name=$(basename $dir).zip
            echo "Archiving $(basename $dir) to $archive_name"
            zip -r $archive_name $dir
        fi
    done
}