#!/bin/sh
#
# Runs the dotfiles installers

set -e

cd "$(dirname $0)"/..

# find the setup scripts and run them iteratively
find . -name setup.sh | while read setup ; do echo "----> Running: ${setup}"; sh -c "${setup}" ; done