#!/bin/sh

function archive () {
    local source_dir=$1
    local dest_dir=$2
    local name=${3:-"data"}

    # Check if the source and destination directories are provided
    if [ -z "$source_dir" ] || [ -z "$dest_dir" ] || [-z "$name" ]; then
        echo "Usage: archive <source_directory> <destination_directory> <name>"
        return 1
    fi

    zip -r "${dest_dir}"/backup-$(date +%Y%m%d)-${name}.zip "${source_dir}"
}