#!/bin/sh

# Create a draft newsletter
function newsletter () {
    local title=${1}
    local workspace_dir=$(workspace "Weary Pilgrim ${title}")
    local sections_dir="${workspace_dir}/sections"
    mkdir -p $sections_dir
    for file in "$RW_TEMPLATES/newsletter/sections/"*; do
        cp $file $sections_dir
    done
    local filename="${workspace_dir}/draft-01.md"
    echo "Creating $filename"
    sed -e "s/\$title/${1}/" "$RW_TEMPLATES/newsletter/newsletter.md" > $filename
    open "$filename"
}