#!/bin/sh

function slugify {
    local target="${1}"

    ## remove non-alphanumeric
    target=$(echo "$target" | tr -cd '[:alnum:]-: ')

    ## replace dash with space
    target=$(echo "$target" | tr '-' ' ')

    ## replace colon with space
    target=$(echo "$target" | tr ':' ' ')

    ## Normalize whitespace
    target=$(echo "$target" | tr -s ' ')

    ## replace whitespace with dash
    target=$(echo "$target" | tr ' ' "-")

    ## normalize dashes
    target=$(echo "$target" | tr -s '-')

    ## convert to lower
    target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

    echo $target
}