#!/bin/sh

# usage: convert-webp-854 input.jpg output.webp 70
function convert-webp-854 () {
    local quality=${3:-60}
    magick "${1}" -resize 854x480^ -gravity center -extent 854x480 -define :webp:lossless=false -define :webp:image-hint=photo -format webp -quality $quality "${2}"
}

function convert-webp-1280 () {
    local quality=${3:-60}
    magick "${1}" -resize 1280x720^ -gravity center -extent 1280x720 -define :webp:lossless=false -define :webp:image-hint=photo -format webp -quality $quality "${2}"
}

function convert-webp-1536 () {
    local quality=${3:-60}
    magick "${1}" -resize 1536x864^ -gravity center -extent 1536x864 -define :webp:lossless=false -define :webp:image-hint=photo -format webp -quality $quality "${2}"
}

function convert-webp-1920 () {
    local quality=${3:-60}
    magick "${1}" -resize 1920x1080^ -gravity center -extent 1920x1080 -define :webp:lossless=false -define :webp:image-hint=photo -format webp -quality $quality "${2}"
}

function webp-lg () {
    local quality=${3:-60}
    magick "${1}" -resize 2560x1440^ -gravity center -extent 2560x1440 -define :webp:lossless=false -define :webp:image-hint=photo -format webp -quality $quality "${2}"  
}

function convert-webp-2560 () {
    local quality=${3:-75}
    magick "${1}" -resize 2560x1440^ -gravity center -extent 2560x1440 -define :webp:lossless=false -define :webp:image-hint=photo -format webp -quality $quality "${2}"  
}